### ISSUE TITLE
Interfere each other

### ISSUE THREAD

**Issue by paullkim** [FThompson/NetflixController#7] opened 2020-05-01 16:03 UTC
PS4 controller, volume and jump back function interfere each other in macOS 10.14.6, seems two functions in same time

**Comment by FThompson** [comment] 2020-05-02 17:11
Thanks for reporting this issue. This is interesting; I wonder if it's an issue with the HTML5 gamepad API, a driver, or something else. I can't recall if I tested the extension on macOS.

Can you answer a few questions to help me diagnose and reproduce the issue?

* Which volume function (up, down, both?) is co-occurring with the jump back function?
* Does the jump forward function work as expected?
* Does this issue occur with other controllers?
* Does this issue occur with the same controller on another operating system, such as Windows?
* What version of Chrome are you using?

**Comment by FThompson** [comment] 2020-06-03 16:22
Further questions:

* In what country do you reside? Netflix varies between locales, so differences there may cause issues.
* On what video(s) does this occur?

**Comment by FThompson** [comment] 2020-10-26 05:24
Unable to reproduce issue; closing.

**Closed as completed by FThompson** 2020-10-26 05:24 UTC
